document.addEventListener("DOMContentLoaded", function () {
  const aiProviderSelect = document.getElementById("ai-provider");
  const apiKeyInput = document.getElementById("api-key");
  const saveSettingsButton = document.getElementById("save-settings");
  const aiResponseDiv = document.getElementById("ai-response");
  const modelInfoDiv = document.getElementById("model-info");
  const loadingIndicator = document.getElementById("loading-indicator");
  const copyResponseButton = document.getElementById("copy-response");
  const insertCodeButton = document.getElementById("insert-code");

  let lastResponse = "";

  chrome.storage.sync.get(["aiProvider", "apiKey"], function (result) {
    if (result.aiProvider) aiProviderSelect.value = result.aiProvider;
    if (result.apiKey) apiKeyInput.value = result.apiKey;
  });

  saveSettingsButton.addEventListener("click", saveSettings);
  copyResponseButton.addEventListener("click", copyResponse);
  insertCodeButton.addEventListener("click", insertCode);

  document.querySelectorAll("[data-ai-action]").forEach((button) => {
    button.addEventListener("click", () => runAction(button.dataset.aiAction));
  });

  function saveSettings() {
    chrome.storage.sync.set(getSettings(), function () {
      showNotification("Settings saved.", "success");
    });
  }

  function getSettings() {
    return {
      aiProvider: aiProviderSelect.value,
      apiKey: apiKeyInput.value,
    };
  }

  function runAction(action) {
    setActiveAction(action);

    const settings = getSettings();
    if (!settings.apiKey) {
      showError("Please paste your API key and click Save first.");
      return;
    }

    chrome.storage.sync.set(settings);
    showLoading(getActionLabel(action));

    chrome.tabs.query({ active: true, currentWindow: true }, function (tabs) {
      const tab = tabs[0];
      if (!tab?.url?.includes("leetcode.com/problems/")) {
        showError("Open a LeetCode problem page first.");
        return;
      }

      getPageContext(tab.id, function (context) {
        if (!context.problemDetails) {
          showError("Could not read problem details. Refresh LeetCode and try again.");
          return;
        }

        const baseSettings = { ...settings, assistanceType: action };
        let payload;

        if (action === "optimize") {
          if (!context.code) {
            showError("Could not read code from the editor.");
            return;
          }
          payload = {
            action: "optimizeCode",
            code: context.code,
            problemDetails: context.problemDetails,
            settings: baseSettings,
          };
        } else if (action === "debug") {
          if (!context.code) {
            showError("Could not read code from the editor.");
            return;
          }
          payload = {
            action: "debugCode",
            code: context.code,
            testCases: context.testCases,
            problemDetails: context.problemDetails,
            settings: baseSettings,
          };
        } else {
          payload = {
            action: "getAIHelp",
            problemDetails: context.problemDetails,
            settings: baseSettings,
          };
        }

        chrome.runtime.sendMessage(payload, function (aiResponse) {
          hideLoading();

          if (chrome.runtime.lastError) {
            showError(chrome.runtime.lastError.message);
            return;
          }

          if (aiResponse?.content) {
            displayResponse(aiResponse.content, aiResponse.model);
            return;
          }

          showError(aiResponse?.error || "Error getting AI response.");
        });
      });
    });
  }

  function setActiveAction(action) {
    document.querySelectorAll("[data-ai-action]").forEach((button) => {
      button.classList.toggle("active", button.dataset.aiAction === action);
    });
  }

  function getPageContext(tabId, done) {
    chrome.tabs.sendMessage(tabId, { action: "getProblemDetails" }, function (problemResponse) {
      chrome.tabs.sendMessage(tabId, { action: "getCurrentCode" }, function (codeResponse) {
        chrome.tabs.sendMessage(tabId, { action: "getTestCases" }, function (testResponse) {
          done({
            problemDetails: problemResponse?.problemDetails,
            code: codeResponse?.code || "",
            testCases: testResponse?.testCases || [],
          });
        });
      });
    });
  }

  function displayResponse(content, model) {
    lastResponse = content || "";
    aiResponseDiv.classList.remove("empty");

    if (typeof marked !== "undefined") {
      aiResponseDiv.innerHTML = marked.parse(lastResponse);
    } else {
      aiResponseDiv.textContent = lastResponse;
    }

    modelInfoDiv.textContent = model ? `Generated by ${model}` : "";
  }

  function showLoading(message) {
    loadingIndicator.textContent = message;
    loadingIndicator.classList.remove("hidden");
    aiResponseDiv.classList.add("empty");
    aiResponseDiv.textContent = message;
    modelInfoDiv.textContent = "";
  }

  function hideLoading() {
    loadingIndicator.classList.add("hidden");
  }

  function showError(message) {
    hideLoading();
    aiResponseDiv.classList.remove("empty");
    aiResponseDiv.innerHTML = `<strong>Error</strong><p>${escapeHtml(message)}</p>`;
    modelInfoDiv.textContent = "";
  }

  function copyResponse() {
    if (!lastResponse) {
      showNotification("Nothing to copy yet.", "warning");
      return;
    }

    navigator.clipboard.writeText(lastResponse).then(
      () => showNotification("Response copied.", "success"),
      () => showNotification("Could not copy response.", "error")
    );
  }

  function insertCode() {
    const code = extractFirstCodeBlock(lastResponse);
    if (!code) {
      showNotification("No code block found in the response.", "warning");
      return;
    }

    chrome.tabs.query({ active: true, currentWindow: true }, function (tabs) {
      chrome.tabs.sendMessage(
        tabs[0].id,
        { action: "insertCode", code },
        function (response) {
          showNotification(
            response?.success ? "Code inserted." : "Could not insert code.",
            response?.success ? "success" : "error"
          );
        }
      );
    });
  }

  function extractFirstCodeBlock(content) {
    const codeMatch = String(content || "").match(/```(?:[\w+-]*)\n([\s\S]*?)```/);
    return codeMatch?.[1]?.trim() || "";
  }

  function getActionLabel(action) {
    const labels = {
      hint: "Preparing a hint...",
      approach: "Building an approach...",
      solution: "Writing a solution...",
      optimize: "Optimizing your code...",
      debug: "Debugging your code...",
      explain: "Explaining the problem...",
    };

    return labels[action] || "Thinking...";
  }

  function showNotification(message, type) {
    const notification = document.createElement("div");
    notification.className = `notification ${type || "info"}`;
    notification.textContent = message;
    document.body.appendChild(notification);

    setTimeout(() => {
      notification.classList.add("fade-out");
      setTimeout(() => notification.remove(), 250);
    }, 2200);
  }

  function escapeHtml(unsafe) {
    return String(unsafe || "")
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#039;");
  }
});
